---
- hosts: victim
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install tcpdump
      apt:
        name: tcpdump
        state: present
        update_cache: yes

    - name: Run tcpdump in background
      shell: tcpdump -i eth0 -w /home/captureB.pcap > /dev/null 2>&1 &
      async: 120
      poll: 0
      become: yes
      register: tcpdump_result

    - name: Wait for tcpdump to start
      async_status:
        jid: "{{ tcpdump_result.ansible_job_id }}"
      register: job_result
      retries: 6
      delay: 10
      until: job_result.finished